# Generated by Django 5.1 on 2024-08-30 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balancete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome do balancete')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação do balancete')),
                ('saldo', models.FloatField(default=0, verbose_name='Saldo total do balancete')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome da transação')),
                ('valor', models.FloatField(verbose_name='Valor da transação')),
                ('boleto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto do boleto da transação')),
                ('balancete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.balancete')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rec', to='financas.transacao')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='des', to='financas.transacao')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
            },
        ),
        migrations.AddField(
            model_name='balancete',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financas.usuario'),
        ),
    ]
