# Generated by Django 5.1 on 2024-08-19 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancete',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário'},
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='balancete',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='boleto',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='balancete',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='boleto',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='valor',
        ),
        migrations.AddField(
            model_name='transacao',
            name='balancete',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='financas.balancete'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacao',
            name='boleto',
            field=models.ImageField(height_field='30', null=True, unique=True, upload_to='', verbose_name='Foto do boleto da transação', width_field='10'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='nome',
            field=models.CharField(default=None, max_length=30, verbose_name='Nome da transação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacao',
            name='valor',
            field=models.FloatField(default=None, verbose_name='Valor da transação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balancete',
            name='nome',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome do balancete'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
