# Generated by Django 5.1 on 2024-09-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financas", "0002_alter_despesa_transacao_alter_receita_transacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transacao",
            name="boleto",
            field=models.ImageField(
                blank=True,
                default="../media/Teste.png",
                null=True,
                upload_to="",
                verbose_name="Foto do boleto da transação",
            ),
        ),
    ]
