# Generated by Django 5.1 on 2024-08-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0003_alter_transacao_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancete',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação do balancete'),
        ),
    ]
