# Generated by Django 5.1 on 2024-08-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0004_alter_balancete_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='boleto',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Foto do boleto da transação'),
        ),
    ]
