# Generated by Django 5.1 on 2024-08-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0005_alter_transacao_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='boleto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto do boleto da transação'),
        ),
    ]
